### ISSUE TITLE
ability to turn off default dungeon spawning

### ISSUE THREAD

**Issue by cole3050** [Globox1997/DungeonZ#1]
### Make sure you are not opening a duplicate.

- [ ] I have searched the issue tracker and did not find an issue describing my bug.

### Description of your suggestion.

Im working on adding my own dungeons thanks to this mod but the default dungeon will not fit my end theme so Im hoping to find a easy way to disable it.

**Comment by Globox1997** [comment]
Added config option with [https://github.com/Globox1997/DungeonZ/commit/729d6645cf04ef8409ef5ef3eba02569cfd14bf3](https://github.com/Globox1997/DungeonZ/commit/729d6645cf04ef8409ef5ef3eba02569cfd14bf3)
