### ISSUE TITLE
Mod Integration[Harder Farther fabric port]

### ISSUE THREAD

**Issue by arazadaz** [Globox1997/DungeonZ#10]
### Make sure you are not opening a duplicate.

- [x] I have searched the issue tracker and did not find an issue describing my bug.

### Description of your suggestion.

Hey I noticed you implemented some integration between rpgdifficulty and your mod. Would you be able to do something similar with the Harder Farther fabric port managed by myself? I'm sure I would have to extend my mod port to do so, but would you be interested? What would you need from my mod port if you were?

Mod listed here: https://legacy.curseforge.com/minecraft/mc-mods/harderfarther-quilt

**Comment by Globox1997** [comment]
I just disabled any rpgdifficulty affection on the dungeons, mobs will get stronger without any other mods.
Not sure what kind of integration you are talking about.

**Comment by Globox1997** [comment]
Seems like you are not working on the mod anymore. I think you can create compatibility between the mods from your side.
