### ISSUE TITLE
[Bug] REI does not wrap around portal gui

### ISSUE THREAD

**Issue by milkev** [Globox1997/DungeonZ#12]
### Minecraft Version

1.20.x

### Mod Loader Version

0.14.22 api 0.87.0

### Mod Version

1.0.2

### Describe the Issue

REI does not wrap around the portal GUI like other gui's do, resulting in REI overlaying part of the interface making it difficult to see and use without turning off REI.
![image](https://github.com/Globox1997/DungeonZ/assets/22010128/ee608f0c-2c0a-4090-80be-98b51bbd0cac)

### latest.log

not relevant

### Do you use any other mods except the required ones?

no

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/DungeonZ/commit/ed771a2bafe2e2a36cf9072d20df7e6e4036dfbb](https://github.com/Globox1997/DungeonZ/commit/ed771a2bafe2e2a36cf9072d20df7e6e4036dfbb)
