### ISSUE TITLE
Creative mode bypasses dungeon join requirements

### ISSUE THREAD

**Issue by milkev** [Globox1997/DungeonZ#14]
### Make sure you are not opening a duplicate.

- [x] I have searched the issue tracker and did not find an issue describing my bug.

### Description of your suggestion.

When joining a dungeon in creative mode, you are still required to have the entry items in your inventory. They arent consumed when joining, but it would just be nice if creative players didnt need to have these items in their inventory in the first place.

**Comment by Globox1997** [comment]
Changed with [https://github.com/Globox1997/DungeonZ/commit/15e034d8ca5ab8e203763d070337a4eebd2a7f8e](https://github.com/Globox1997/DungeonZ/commit/15e034d8ca5ab8e203763d070337a4eebd2a7f8e)
