### ISSUE TITLE
Add a minimum group size as a settings in a dungeon json

### ISSUE THREAD

**Issue by chemicalursine** [Globox1997/DungeonZ#15]
### Make sure you are not opening a duplicate.

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### Description of your suggestion.

Allow to define a minimum group size in the settings on a dungeon for dungeons you wish to "force" players to play in group. Could be useful if some dungeon rooms requires 2 or more people to complete.

**Comment by Globox1997** [comment]
Added with [https://github.com/Globox1997/DungeonZ/commit/6cdb1eb35ba33797503a0649ec21158265327711](https://github.com/Globox1997/DungeonZ/commit/6cdb1eb35ba33797503a0649ec21158265327711)
Hopefully everything works as intended, otherwise please reopen this issue with further information!
