### ISSUE TITLE
Impossible to use creatures that depends on dimension type in dungeons

### ISSUE THREAD

**Issue by chemicalursine** [Globox1997/DungeonZ#16]
### Minecraft Version

1.20.x

### Mod Loader Version

fabric-loader-0.14.22-1.20.1

### Mod Version

dungeonz-1.0.2+1.20.1

### Describe the Issue

It's not really a bug, more of half a suggestion, half a issue, 
Currently if you want to use Piglins or Hoglins in your dungeons, it's impossible because of the zombificiation of both these mobs. I consider this a bug since it incapacitates ability to make certain types of dungeon at all.

### latest.log

Not necessary

**Comment by Globox1997** [comment]
Added `dungeonz:immune_to_zombification` entity tag which prevents all entities from zombification when spawned inside the dungeon.
