### ISSUE TITLE
Open ceiling brightness

### ISSUE THREAD

**Issue by thrasos-dev** [Globox1997/DungeonZ#17]
### Minecraft Version

1.20.x

### Mod Loader Version

0.14.22

### Mod Version

1.0.2

### Describe the Issue

Not sure if this is a bug or intended, but when we made an open section in our dungeon, we expected it to be bright, but it was still dark, as if no light came in from above.

![image](https://github.com/Globox1997/DungeonZ/assets/100732009/1acdb5e9-7b08-46a7-bd50-9b86ec3bb9b5)

If this is intended, is there any way to configure it?

### latest.log

[latest.log](https://github.com/Globox1997/DungeonZ/files/13022023/latest.log)

**Comment by Globox1997** [comment]
Was intended but I changed it with [https://github.com/Globox1997/DungeonZ/commit/9777a48a841a0b21cbdd0e84008f66a09a231a45](https://github.com/Globox1997/DungeonZ/commit/9777a48a841a0b21cbdd0e84008f66a09a231a45)

**Comment by Globox1997** [comment]
Had to reverse this cause behind skyLight is more than just the sky light.
Weather, multiple mob spawns and other mechanics depend on this boolean.

**Comment by thrasos-dev** [comment]
I see, so it is much more involved. We will refrain from using open sections in the future. Thanks for the try.
