### ISSUE TITLE
Repeatedly enter the dungeon

### ISSUE THREAD

**Issue by Karashok-Leo** [Globox1997/DungeonZ#21]
### Minecraft Version

1.20.x

### Mod Loader Version

0.91.0

### Mod Version

1.0.3

### Describe the Issue

I was testing this mod in the creative mode. When I stand in the portal block, the block notes down my posion and sends me into the dimension. Then I used command to leave the dungeon, backing to the position that had been recorded, being sended into the dimension again...... Maybe teleporting player by touching the portal is not a good idea. By the way, the portal doesn't look like a block with configurable screen.

### latest.log

no log

**Comment by Globox1997** [comment]
I see

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/DungeonZ/commit/de4dbd2a6dbb753fecc8c9d184f53e7928213030](https://github.com/Globox1997/DungeonZ/commit/de4dbd2a6dbb753fecc8c9d184f53e7928213030)
