### ISSUE TITLE
I died in the dungeon and i can not go back in go get my stuff

### ISSUE THREAD

**Issue by CarsonCoffta** [Globox1997/DungeonZ#26]
### Minecraft Version

1.20.x

### Mod Loader Version

1.19.2

### Mod Version

1.19.2

### Describe the Issue

i entered the dungeon while on the medieval mod pack and I miss a parkour jump and fell on lava and magma blocks and had no choice but to die, now i can not go retrieve my gravestone because I can not get back to the dimension, the server owner tried to help me get there. Is there a command to tp to that dimension?

### latest.log

i entered the dungeon while on the medieval mod pack and I miss a parkour jump and fell on lava and magma blocks and had no choice but to die, now i can not go retrieve my gravestone because I can not get back to the dimension, the server owner tried to help me get there. Is there a command to tp to that dimension?

### Do you use any other mods except the required ones?

medieval mod pack

**Comment by Globox1997** [comment]
Sounds actually like a good idea to add a respawn option for dungeons.

**Comment by Globox1997** [comment]
Introduced respawning in dungeons (as a datapack option, default true) in a later version.
