### ISSUE TITLE
Dungeonz keeps trying to ask nothing to do something

### ISSUE THREAD

**Issue by poseidoncarrot** [Globox1997/DungeonZ#28]
### Minecraft Version

1.20.x

### Mod Loader Version

0.15.11

### Mod Version

1.0.5

### Describe the Issue

The server that I'm running Dungeonz on constantly keep crashing everytime it starts up which creates a loop of crashing and restarting. The crash logs below show that its due to dungeonz is constantly trying to get the dungeon that the player is in but forgets to check if there even is a player to check to begin with so it basically just tried to check a null value. So basically it just keeps trying to get nothing to do something which is causing the crashes.

[crash-2024-06-17_01.05.35-server.txt](https://github.com/user-attachments/files/15860464/crash-2024-06-17_01.05.35-server.txt)

### latest.log

[2024-06-17-1.log](https://github.com/user-attachments/files/15860460/2024-06-17-1.log)

### Do you use any other mods except the required ones?

There are 184 other mods as seen in the logs above and the crash logs, also above, clearly shows that its Dungeonz problem.

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/DungeonZ/commit/41345a61486a8c277cedf0ae58f643f8c51e2c85](https://github.com/Globox1997/DungeonZ/commit/41345a61486a8c277cedf0ae58f643f8c51e2c85)
