### ISSUE TITLE
datapack example

### ISSUE THREAD

**Issue by RazzerSSS** [Globox1997/DungeonZ#4]
### Make sure you are not opening a duplicate.

- [x] I have searched the issue tracker and did not find an issue describing my bug.

### Description of your suggestion.

I would like to see an example of a datapack for the dungeonz mod, how to create it, so that in this example I can create my own datapacks with dungeons

**Comment by Globox1997** [comment]
An example can be found now at this repository, added with [https://github.com/Globox1997/DungeonZ/commit/0f927daab9c84348b7375e82fd7559939d19a62f](https://github.com/Globox1997/DungeonZ/commit/0f927daab9c84348b7375e82fd7559939d19a62f)
