### ISSUE TITLE
Dungeon cooldown and unloaded chunks

### ISSUE THREAD

**Issue by SCPRedMage** [Globox1997/DungeonZ#5]
### Make sure you are not opening a duplicate.

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### Description of your suggestion.

The dungeon cooldown doesn't seem to progress if the entrance is in an unloaded chunk; requiring players to forceload chunks to keep the timer going is probably a bad idea.

**Comment by Globox1997** [comment]
This is right, it is not the best idea.

**Comment by Globox1997** [comment]
Changed it to use time difference with [https://github.com/Globox1997/DungeonZ/commit/24b48b6ea8b29b1334a7a57ea615aff8a91c3b3d](https://github.com/Globox1997/DungeonZ/commit/24b48b6ea8b29b1334a7a57ea615aff8a91c3b3d)
