### ISSUE TITLE
GUI cooldown display is incorrect

### ISSUE THREAD

**Issue by SCPRedMage** [Globox1997/DungeonZ#7]
### Minecraft Version

1.19.x

### Mod Loader Version

0.14.21

### Mod Version

1.0.1

### Describe the Issue

When viewing the cooldown for the dungeon in the GUI, the time shown is incorrect. With the default Dark Dungeon, it shows a time starting at 30 hours, and decreases much faster than normal.

I believe what's happening is that the GUI is treating the ticks remaining in the cooldown as seconds, as 108000 seconds is 30 hours.

### latest.log

No log included, as there is no crash and this wouldn't show up in the log.

**Comment by Globox1997** [comment]
Thanks for reporting and the info, fixed with [https://github.com/Globox1997/DungeonZ/commit/9c120952dee2e359cdfd90d7f12d45f507473afe](https://github.com/Globox1997/DungeonZ/commit/9c120952dee2e359cdfd90d7f12d45f507473afe)
