### ISSUE TITLE
Mob spawn probabilities broken

### ISSUE THREAD

**Issue by thrasos-dev** [Globox1997/DungeonZ#8]
### Minecraft Version

1.20.x

### Mod Loader Version

0.14.21

### Mod Version

1.0.1

### Describe the Issue

After setting the probability of all difficulty mob spawns to `1.0`, none of the mobs spawn.

Relevant code snippet from the config:
```json
    "minecraft:green_wool": {
      "spawns": [
        "minecraft:skeleton"
      ],
      "chance": {
        "easy": 1.0,
        "normal": 1.0,
        "hard": 1.0
      },
      "replace": "minecraft:air"
    }
```

### latest.log

[latest.log](https://github.com/Globox1997/DungeonZ/files/12030741/latest.log)

**Comment by Globox1997** [comment]
Thanks for reporting, fixed with [https://github.com/Globox1997/DungeonZ/commit/e6e74654211072430364e10d519778d354ec7d99](https://github.com/Globox1997/DungeonZ/commit/e6e74654211072430364e10d519778d354ec7d99)
