### ISSUE TITLE
Unable to set breakable and placeable blocks in dungeons

### ISSUE THREAD

**Issue by GlitchedGekko** [Globox1997/DungeonZ#9]
### Minecraft Version

1.19.x

### Mod Loader Version

Fabric 0.14.21

### Mod Version

1.0.1

### Describe the Issue

I followed the instructions and format on the github page in order to determine which blocks are placeable and breakable within a dungeon. But when I've set any blocks, they are still unbreakable in the dungeons, even the default placing of torches does not work.

### latest.log

N/A

### Do you use any other mods except the required ones?

Some optimization mods, sodium, lithium, indium

**Comment by Globox1997** [comment]
Syncing time was wrong, fixed with [https://github.com/Globox1997/DungeonZ/commit/a966813755301349723bb5bc78ff0c90a2e956b8](https://github.com/Globox1997/DungeonZ/commit/a966813755301349723bb5bc78ff0c90a2e956b8)
